#!/usr/bin/env sh

set -e

if [ $# -lt 2 ]; then
  echo "❗️  No sync source and destination specified."
  exit 1
fi

if [ ! -d "$1" ]; then
  echo "❗️  Source $1 does not exist."
  exit 1
fi

if [ ! -d "$2" ]; then
  echo "❗️  Destination $2 does not exist."
  exit 1
fi

echo "⚙️  Syncing $1 into $2"
echo
echo "📄  Files to be synced:"

rsync -avin --delete --size-only --exclude=".DS_Store" "$1"/* "$2"/ | grep '^*\|^>' | more

echo 
while true; do
    read -p "❓  Do you wish to continue with sync? [y/n] " yn
    case $yn in
        [Yy]* ) rsync -av --delete --size-only --exclude=".DS_Store" "$1"/* "$2"/; break;;
        [Nn]* ) exit;;
        * ) echo "😨  Please provide a y/n answer.";;
    esac
done

echo
echo "✅  Sync complete!"
